# Generated by Django 4.0.1 on 2022-01-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compozitii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=150)),
                ('an_aparitie', models.SmallIntegerField()),
                ('gen', models.CharField(max_length=45)),
                ('gama', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('nr_instrumente', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compozitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
                ('stil', models.CharField(max_length=45)),
                ('tara_origine', models.CharField(max_length=45)),
                ('data_nasterii', models.DateField()),
                ('data_mortii', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cataloage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=15)),
                ('compozitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.compozitii')),
                ('compozitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.compozitori')),
            ],
        ),
    ]
